INFO:TeleBot:Started polling.
ERROR:TeleBot:NameError occurred, args=("name 'msg' is not defined",)
Traceback (most recent call last):
  File "C:\Users\THANHHIEU\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "C:\Users\THANHHIEU\Desktop\flibusta_bot-master\src\debug_utils.py", line 16, in timer
    return foo(*arg, **kwargs)
  File "main.py", line 123, in bot_search_by_title
    if len(msg.reply_to_message.text) < 4:
NameError: name 'msg' is not defined

